[general]
static=yes
writeprotect=no

[default]
exten => _X.,1,NoOp(Llamada a ${EXTEN})
same => n,Dial(PJSIP/${EXTEN},20)
same => n,Hangup()

; Extensión de prueba
exten => 1010,1,Answer()
same => n,Playback(hello-world)
same => n,Hangup()